# Tensorflow : Basic to Advanced
#### Tensors
"A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes." (https://www.tensorflow.org/guide/tensor)

It should't surprise you that tensors are a fundemental apsect of TensorFlow. They are the main objects that are passed around and manipluated throughout the program. Each tensor represents a partialy defined computation that will eventually produce a value. TensorFlow programs work by building a graph of Tensor objects that details how tensors are related. Running different parts of the graph allow results to be generated.

Each tensor has a data type and a shape.

Data Types Include: float32, int32, string and others.

Shape: Represents the dimension of data.

Just like vectors and matrices tensors can have operations applied to them like addition, subtraction, dot product, cross product etc.

In the next sections we will discuss some different properties of tensors. This is to make you more familiar with how tensorflow represnts data and how you can manipulate this data.

In [ ]:
# installing tensorflow through pip
! pip install tensorflow

In [ ]:
# make sure the version of tensorflow
%tensorflow_version 2.x

In [ ]:
# importing tensorflow
import tensorflow as tf
print(tf.version)

#### Creating Tensors :
- here is an example of how to create some different tensors.

- You simply define the value of the tensor and the datatype and you are good to go! It's worth mentioning that usually we deal with tensors of numeric data, it is quite rare to see string tensors.

- For a full list of datatypes please refer to the following guide.

In [ ]:
# creating few different tensors
string=tf.Variable('this is a string', tf.string)
# we have also int8,int16 and int32
number=tf.Variable(7,tf.int64)
# we have also float32,float64
floatting=tf.Variable(7.77,tf.float16)
# type of tensors vatriable
type(string)

# Rank or Degree of Tensor
##### Rank/Degree of Tensors
- Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor.
- What we created above is a tensor of rank 0, also known as a scalar.-
Now we'll create some tensors of higher degrees/ranks.

In [ ]:
# rank/degree : this term simply mean the number of dimensions involved in the tensor
# rank_01, rank_02 and rank_03 involve 1, 2 and 3 respectively.
# To determine the rank of a tensor we can call the following method.
rank_01=tf.Variable(['test'],tf.string)
rank_02=tf.Variable([['test','ok'],['test','yes']],tf.string)
rank_03=tf.Variable([['test','happening','here'],['Mehedi','Hasan','ocean'],['google','Myjob','djob']],tf.string)
print(tf.rank(rank_01),tf.rank(rank_02),tf.rank(rank_03))

The rank of a tensor is direclty related to the deepest level of nested lists. You can see in the first example ["Test"] is a rank 1 tensor as the deepest level of nesting is 1. Where in the second example [["test", "ok"], ["test", "yes"]] is a rank 2 tensor as the deepest level of nesting is 2.

#### Shape of tensors :
- The shape of tensors are simply the amount of elements that exist in each dimension.
- Tensorflow will try to determine the shape of a tensor but sometimes it may be unknown.

In [ ]:
# shape of the tensors as TensorShape
rank_01.shape # shape is 1
rank_02.shape # shape is [2,2]
rank_03.shape # shape is [3,3]

#### Changing Shape
- The number of elements of a tensor is the product of the sizes of all its shapes.
- There are often many shapes that have the same number of elements, making it convient to be able to change the shape of a tensor.
- The example below shows how to change the shape of a tensor.

In [3]:
# tf.ones() creates a shape [1,2,3] tensor full of ones
tensor1 = tf.ones([1,2,3])
# reshape existing data to shape [2,3,1]
tensor2 = tf.reshape(tensor1, [2,3,1])
# -1 tells the tensor to calculate the size of the dimension in that place
# this will reshape the tensor to [3,2]
tensor3 = tf.reshape(tensor2, [3, -1])

# Note : The numer of elements in the reshaped tensor MUST match the number in the original tensor

In [ ]:
# printing the all tensor
print(tensor1)
print(tensor2)
print(tensor3)

### Slicing Tensors
- we may be familiar with the term "slice" in python and its use on lists, tuples etc. Well the slice operator can be used on tensors to select specific axes or elements.

- When we slice or select elements from a tensor, we can use comma seperated values inside the set of square brackets. Each subsequent value refrences a different dimension of the tensor.

Ex: tensor[dim1, dim2, dim3]

I've included a few examples that will hopefully help illustrate how we can manipulate tensors with the slice operator.

In [ ]:
# Creating a 2D tensor
# shape : we have 4 list and each list has 5 elements and all the things inside a interior list
# rank is the dimension means it has 2 dimension of data
# the data type is int32
# we calling Variable() function through tensorflow and push the matrix into the trensors varibale as 'tensor'
# output :
# tf.Tensor(2, shape=(), dtype=int32)
# (4, 5)
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32)
print(tf.rank(tensor))
print(tensor.shape)

In [ ]:
# Now lets select some different rows and columns from our tensor

three = tensor[0,2]  # selects the 3rd element from the 1st row
print(three)  # -> 3

row1 = tensor[0]  # selects the first row
print(row1)

column1 = tensor[:, 0]  # selects the first column
print(column1)

row_2and_4 = tensor[1::2]  # selects second and fourth row
print(row_2and_4)

column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)
# output :
# tf.Tensor(3, shape=(), dtype=int32)
# tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
# tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
# tf.Tensor([[ 6  7  8  9 10][16 17 18 19 20]], shape=(2, 5), dtype=int32)
# tf.Tensor([ 6 11], shape=(2,), dtype=int32)

### Types of Tensors
There are diffent types of tensors. These are the most used and we will talk more in depth about each when they are used.

- Variable
- Constant
- Placeholder
- SparseTensor

all the tensors execpt Variable are immuttable, meaning their value may not change during execution.

For now, it is enough to understand that we use the Variable tensor when we want to potentially change the value of our tensor.

Sources :
Most of the information is taken direclty from the TensorFlow website which can be found below.

https://www.tensorflow.org/guide/tensor